[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
FLASK_ENV = "production"
FLASK_PORT = "5000"
WEB_CONCURRENCY = "2"