name: ULTRASYNC Production Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [vercel, railway, render]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r rccm-quiz-app/requirements.txt
        
    - name: Test application safety
      run: |
        cd rccm-quiz-app
        python -c "from app import app; print('✅ Application syntax verified')"
        python -c "from wsgi_optimized import application; print('✅ WSGI configuration verified')"
        
    - name: Deploy to Vercel
      if: matrix.platform == 'vercel'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./rccm-quiz-app
        
    - name: Deploy to Railway
      if: matrix.platform == 'railway'
      uses: bervProject/railway-deploy@v1.0.0
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE }}
        
    - name: Deploy to Render
      if: matrix.platform == 'render'
      run: |
        echo "Render deployment triggered via webhook"
        # Render auto-deploys from GitHub when connected