name: RCCM App Reality Test (Final Version)

on:
  push:
    branches: [ "main", "master", "develop" ]
  workflow_dispatch:

jobs:
  test-on-real-environment:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./rccm-quiz-app

    steps:
    - name: 1. Checkout repository code
      uses: actions/checkout@v4

    - name: 2. Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Install Google Chrome
      defaults:
        run:
          working-directory: .
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

    - name: 4. Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install selenium webdriver-manager

    - name: 5. Start Flask server in background
      run: |
        flask --app app run &
        sleep 10
        echo "サーバー起動確認中..."
        curl --fail http://127.0.0.1:5000/

    - name: 6. Run the actual browser test from your file
      run: python rccm_flask_auto_test.py

    - name: 7. Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reality-test-results
        path: ./rccm-quiz-app/test_results_*.json