services:
  - type: web
    name: rccm-quiz-ultrasync
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --log-level debug --access-logfile - --error-logfile - wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: HTTPS
        value: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    branch: master