services:
  - type: web
    name: rccm-quiz-ultrasync
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload --pythonpath . app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: HTTPS
        value: "true"
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: "10000"
    autoDeploy: true
    branch: master