services:
  - type: web
    name: rccm-quiz-2025-complete
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 180 --preload app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PYTHONPATH
        value: ./rccm-quiz-app
    autoDeploy: true
    branch: master