services:
  - type: web
    name: rccm-quiz-2025
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    disk:
      name: rccm-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1